---
application:
  name: "user-node-js"
  project: "users-get-add"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "users"
  version: "8.0"
routers:
- name: "main-user-node-js"
  routes:
  - application_name: "user-node-js"
    paths:
    - "/*"
